# Generated by Django 5.2.8 on 2026-06-19 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0016_course_estimated_hours_course_is_active_and_more'),
        ('payments', '0003_remove_paymentorderitem_amount_paise_and_more'),
        ('students', '0006_goal_goal_type_goal_last_checkin_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('program_type', models.CharField(choices=[('long_term', 'Long-Term Program'), ('fast_track', 'Fast-Track Program'), ('cohort', 'Cohort Program'), ('self_paced', 'Self-Paced Program')], default='long_term', max_length=30)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(default=0)),
                ('total_hours', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('promo_video_url', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-published_at', 'title'],
                'indexes': [models.Index(fields=['is_published', 'is_featured'], name='programs_le_is_publ_39d226_idx'), models.Index(fields=['slug'], name='programs_le_slug_1edcc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='programs.learningprogram')),
            ],
            options={
                'ordering': ['program', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='programs.learningprogram')),
            ],
            options={
                'ordering': ['program', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('duration_weeks', models.PositiveIntegerField(default=0)),
                ('starts_at_week', models.PositiveIntegerField(blank=True, null=True)),
                ('ends_at_week', models.PositiveIntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='programs.learningprogram')),
            ],
            options={
                'ordering': ['program', 'order', 'id'],
                'unique_together': {('program', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProgramPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.PositiveIntegerField()),
                ('min_final_price_paise', models.PositiveIntegerField(default=0)),
                ('max_negotiation_paise', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='programs.learningprogram')),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='active', max_length=20)),
                ('progress', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_enrollments', to='payments.paymentorder')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='programs.learningprogram')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'status'], name='programs_pr_student_b2cb3e_idx'), models.Index(fields=['program', 'status'], name='programs_pr_program_30ab6b_idx')],
                'unique_together': {('student', 'program')},
            },
        ),
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('unlock_after_days', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_links', to='courses.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='programs.learningprogram')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_courses', to='programs.programphase')),
            ],
            options={
                'ordering': ['program', 'phase__order', 'order', 'id'],
                'indexes': [models.Index(fields=['program', 'phase', 'order'], name='programs_pr_program_e31482_idx')],
                'unique_together': {('program', 'course')},
            },
        ),
    ]
