# Generated by Django 5.2.8 on 2026-06-19 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role__in': ['faculty', 'trainer']}, on_delete=django.db.models.deletion.CASCADE, related_name='public_faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['slug'], name='faculty_fac_slug_d3f4ce_idx'), models.Index(fields=['is_public'], name='faculty_fac_is_publ_b71745_idx')],
            },
        ),
    ]
