# Generated by Django 5.2.8 on 2026-02-23 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Super Admin"),
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("trainer", "Trainer"),
                    ("sales_admin", "Sales Admin"),
                    ("sales_manager", "Sales Manager"),
                    ("sales_exec", "Sales Executive"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
