# Generated by Django 5.2.8 on 2026-04-22 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0003_institution_email_and_more"),
        ("users", "0004_customuser_manager_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Super Admin"),
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("trainer", "Trainer"),
                    ("institution_admin", "Institution Admin"),
                    ("hod", "Head of Department"),
                    ("sales_admin", "Sales Admin"),
                    ("sales_manager", "Sales Manager"),
                    ("sales_exec", "Sales Executive"),
                ],
                db_index=True,
                default="student",
                max_length=20,
            ),
        ),
    ]
