export * from "./common";
export * from "./dashboard";
export * from "./people";
export * from "./academic";
export * from "./attendance";
export * from "./timetable";
export * from "./grades";
export * from "./reports";
export * from "./operations";
