# Generated by Django 5.2.8 on 2025-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('course', 'Course'), ('module', 'Module'), ('study', 'Study'), ('assessment', 'Assessment')], default='study', max_length=50),
        ),
    ]
