# Generated by Django 5.2.8 on 2025-11-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('study', 'Study'), ('course', 'Course'), ('assessment', 'Assessment')], default='study', max_length=20),
        ),
    ]
