# Generated by Django 5.2.8 on 2025-11-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_task_category_goal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('progress', 'Progress Goal'), ('habit', 'Daily Habit')], default='progress', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='last_checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
