# Generated by Django 5.2.8 on 2026-04-21 03:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import institution.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="institution",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="admin",
            field=models.ForeignKey(
                limit_choices_to={"role": "institution_admin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administered_institutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="attendance_threshold",
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name="institution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institution",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="modules_config",
            field=models.JSONField(default=institution.models.default_modules),
        ),
        migrations.AddField(
            model_name="institution",
            name="mou_reference",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="institution",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="primary_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="institution",
            name="seat_limit",
            field=models.IntegerField(
                default=500, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("offboarded", "Offboarded"),
                ],
                db_index=True,
                default="active",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="tier",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                ],
                default="basic",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
