# Generated by Django 5.2.8 on 2026-04-22 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0002_alter_institution_options_institution_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="attendance_threshold",
            field=models.IntegerField(
                default=75,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
