# Generated by Django 5.2.8 on 2026-04-27 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0006_timeslot_alter_degree_institution_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_marks", models.FloatField()),
                ("max_marks", models.FloatField()),
                ("grade", models.CharField(max_length=2)),
                ("grade_point", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_scales",
                        to="institution.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["-min_marks"],
                "unique_together": {("institution", "grade")},
            },
        ),
    ]
