# Generated by Django 5.2.8 on 2026-05-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0007_gradescale"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
