# Generated by Django 5.2.8 on 2026-05-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0008_timeslot_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="hod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="institution.facultyprofile",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_teacher_sections",
                to="institution.facultyprofile",
            ),
        ),
    ]
