# Generated by Django 5.2.8 on 2026-06-26 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0009_alter_department_hod_alter_section_class_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('student_created', 'Student Created'), ('student_updated', 'Student Updated'), ('student_suspended', 'Student Suspended'), ('student_promoted', 'Student Promoted'), ('student_bulk_import', 'Student Bulk Import'), ('faculty_created', 'Faculty Created'), ('faculty_updated', 'Faculty Updated'), ('faculty_suspended', 'Faculty Suspended'), ('faculty_reactivated', 'Faculty Reactivated'), ('faculty_offboarded', 'Faculty Offboarded'), ('faculty_made_hod', 'Faculty Made HOD'), ('attendance_unlocked', 'Attendance Unlocked'), ('grade_overridden', 'Grade Overridden'), ('result_published', 'Result Published'), ('academic_structure_changed', 'Academic Structure Changed')], db_index=True, max_length=80)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=80)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='institution.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='institution.institution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'action'], name='institution_institu_c5e2ee_idx'), models.Index(fields=['institution', 'department'], name='institution_institu_fbe14e_idx'), models.Index(fields=['target_type', 'target_id'], name='institution_target__b5248c_idx')],
            },
        ),
    ]
