# Generated by Django 5.2.8 on 2026-06-26 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0010_institutionauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionauditlog',
            name='action',
            field=models.CharField(choices=[('student_created', 'Student Created'), ('student_updated', 'Student Updated'), ('student_suspended', 'Student Suspended'), ('student_promoted', 'Student Promoted'), ('student_bulk_import', 'Student Bulk Import'), ('faculty_created', 'Faculty Created'), ('faculty_updated', 'Faculty Updated'), ('faculty_suspended', 'Faculty Suspended'), ('faculty_reactivated', 'Faculty Reactivated'), ('faculty_offboarded', 'Faculty Offboarded'), ('faculty_made_hod', 'Faculty Made HOD'), ('attendance_unlocked', 'Attendance Unlocked'), ('grade_overridden', 'Grade Overridden'), ('result_published', 'Result Published'), ('leave_applied', 'Leave Applied'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('export_requested', 'Export Requested'), ('export_completed', 'Export Completed'), ('export_failed', 'Export Failed'), ('academic_structure_changed', 'Academic Structure Changed')], db_index=True, max_length=80),
        ),
        migrations.CreateModel(
            name='InstitutionExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('students', 'Students'), ('faculty', 'Faculty'), ('attendance', 'Attendance'), ('performance', 'Performance'), ('faculty_activity', 'Faculty Activity'), ('batch_performance', 'Batch Performance')], max_length=40)),
                ('export_format', models.CharField(choices=[('csv', 'CSV')], default='csv', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('file', models.FileField(blank=True, upload_to='exports/institution/')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='institution.institution')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'report_type'], name='institution_institu_799c89_idx'), models.Index(fields=['requested_by', 'status'], name='institution_request_4795cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('document_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='institution.institution')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='institution.institutionstudent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'status'], name='institution_institu_85d647_idx'), models.Index(fields=['student', 'from_date', 'to_date'], name='institution_student_c8a784_idx')],
            },
        ),
    ]
