# Generated by Django 5.2.8 on 2026-06-29 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0011_alter_institutionauditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='institution/leave_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='institution.facultyprofile'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='institution.institutionstudent'),
        ),
    ]
