# Generated by Django 5.2.8 on 2026-04-09 11:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_enrollment_courses_enr_student_774ec5_idx"),
        ("payments", "0002_alter_commission_amount_paise_and_more"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentorderitem",
            name="amount_paise",
        ),
        migrations.AddField(
            model_name="courseprice",
            name="max_negotiation_paise",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="courseprice",
            name="min_final_price_paise",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="paymentorderitem",
            name="base_amount_paise",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentorderitem",
            name="discount_paise",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="paymentorderitem",
            name="final_amount_paise",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentorderitem",
            name="negotiation_paise",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CourseDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_paise",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_links",
                        to="courses.course",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_links",
                        to="sales.lead",
                    ),
                ),
                (
                    "sales_exec",
                    models.ForeignKey(
                        limit_choices_to={"role": "sales_exec"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
