# Generated by Django 5.2.8 on 2026-06-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_course_faculty_remove_course_instructor_image_and_more'),
        ('programs', '0001_initial'),
        ('public_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('focus_area', models.CharField(blank=True, max_length=120)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['roadmap', 'display_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='roadmapstep',
            options={'ordering': ['roadmap', 'track__display_order', 'display_order', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='careerpath',
            name='public_cont_status_b55f38_idx',
        ),
        migrations.RemoveIndex(
            model_name='roadmap',
            name='public_cont_status_eecdce_idx',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='career_path',
        ),
        migrations.AddField(
            model_name='careerpath',
            name='hiring_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='opportunity_count_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='related_roadmaps',
            field=models.ManyToManyField(blank=True, related_name='related_career_paths', to='public_content.roadmap'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='role_family',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='roadmap_type',
            field=models.CharField(choices=[('domain', 'Domain Roadmap'), ('role', 'Role Roadmap'), ('skill', 'Skill Roadmap'), ('track', 'Track Roadmap')], default='domain', max_length=30),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='concepts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='duration_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='stage_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='publicdomain',
            index=models.Index(fields=['status', 'is_featured'], name='public_cont_status_574ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='publicdomain',
            index=models.Index(fields=['slug'], name='public_cont_slug_5cffe2_idx'),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_paths', to='public_content.publicdomain'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmaps', to='public_content.publicdomain'),
        ),
        migrations.AddIndex(
            model_name='careerpath',
            index=models.Index(fields=['status', 'is_featured'], name='public_cont_status_c21021_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['status', 'roadmap_type', 'is_featured'], name='public_cont_status_8453fe_idx'),
        ),
        migrations.AddField(
            model_name='roadmaptrack',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='public_content.roadmap'),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='public_content.roadmaptrack'),
        ),
        migrations.AlterUniqueTogether(
            name='roadmaptrack',
            unique_together={('roadmap', 'slug')},
        ),
    ]
