export * from "./dashboard.api";
export * from "./people.api";
export * from "./academic.api";
export * from "./timetable.api";
export * from "./attendance.api";
export * from "./grades.api";
export * from "./reports.api";
export * from "./audit.api";
export * from "./exports.api";
