# Generated by Django 5.2.8 on 2025-11-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_module_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('self_paced', 'Self-Paced Course'), ('instructor_led', 'Instructor-Led Course')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
