# Generated by Django 5.2.8 on 2025-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_type_course_deadline_lesson_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('self_paced', 'Self-Paced Course'), ('instructor_led', 'Instructor-Led Course')], default='premade', max_length=20),
        ),
    ]
