# Generated by Django 5.2.8 on 2025-11-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('self_paced', 'Self-Paced Course'), ('instructor_led', 'Instructor-Led Course')], default='self_paced', max_length=20),
        ),
    ]
