# Generated by Django 5.2.8 on 2025-12-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_course_domain_course_language_course_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="video_url",
            new_name="resource_url",
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("video", "Video Lesson"),
                    ("reading", "Reading"),
                    ("lab", "Interactive Lab"),
                ],
                default="video",
                max_length=20,
            ),
        ),
    ]
