# Generated by Django 5.2.8 on 2026-04-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_rename_video_url_lesson_resource_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="price",
        ),
    ]
