# Generated by Django 5.2.8 on 2026-04-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_remove_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
