# Generated by Django 5.2.8 on 2026-04-09 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_enrollment_is_active"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="payments.paymentorder",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="price_paid",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
