# Generated by Django 5.2.8 on 2026-04-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_enrollment_order_enrollment_price_paid"),
        ("payments", "0002_alter_commission_amount_paise_and_more"),
        ("students", "0006_goal_goal_type_goal_last_checkin_date"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "course"], name="courses_enr_student_774ec5_idx"
            ),
        ),
    ]
