# Generated by Django 5.2.8 on 2026-06-19 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_enrollment_courses_enr_student_774ec5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('promo_video_url', models.URLField(blank=True, null=True)),
                ('instructor_name', models.CharField(blank=True, max_length=150)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='courses.course')),
            ],
            options={
                'ordering': ['order', '-published_at', 'title'],
                'indexes': [models.Index(fields=['is_published', 'is_featured'], name='courses_cou_is_publ_143790_idx'), models.Index(fields=['slug'], name='courses_cou_slug_9a4f42_idx')],
            },
        ),
    ]
