# Generated by Django 5.2.8 on 2026-06-19 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_estimated_hours_course_is_active_and_more'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='course',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='promo_video_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseproduct',
            name='display_price_paise',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseproduct',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='course_products', to='faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='courseproduct',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseproduct',
            name='instructor_name',
            field=models.CharField(blank=True, help_text='Legacy/display fallback when no faculty profiles are attached.', max_length=150),
        ),
    ]
