# Generated by Django 5.2.8 on 2026-02-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_rename_video_url_lesson_resource_url_and_more"),
        ("live_classes", "0002_liveclassattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveclass",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="live_classes",
                to="courses.lesson",
            ),
        ),
    ]
