# Generated by Django 5.2.8 on 2026-03-25 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0011_rename_video_url_lesson_resource_url_and_more"),
        ("students", "0006_goal_goal_type_goal_last_checkin_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credential_id",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
                "unique_together": {("student", "course")},
            },
        ),
    ]
